Repository jenkinsci/versionnumber-plugin, pull requests merged in 2025-02, with the labels that each got.

#91 Require Jenkins 2.479.1, Java 17, and Jakarta EE 9
  pom.xml
  src/main/java/org/jvnet/hudson/tools/versionnumber/VersionNumberBuilder.java
Labels: chore

#93 Use Java 17 text blocks
  src/test/java/org/jvnet/hudson/tools/versionnumber/VersionNumberStepTest.java
Labels: chore

#92 Enable continuous delivery
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#94 Migrate tests to JUnit5
  src/test/java/org/jvnet/hudson/tools/versionnumber/VersionNumberBuilderTest.java
  src/test/java/org/jvnet/hudson/tools/versionnumber/VersionNumberStepTest.java
Labels: test
